"""modelos

Revision ID: 4220b3f94893
Revises: 
Create Date: 2025-02-21 16:52:10.949876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4220b3f94893'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('parking_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'parking', ['parking_id'], ['parking_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('matricula')

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parking_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'parking', ['parking_id'], ['parking_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('import_price')
        batch_op.drop_column('plate')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('reservation_start_time')
        batch_op.drop_column('vehicle_type')
        batch_op.drop_column('reservation_end_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['plate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('plate')

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_end_time', mysql.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column('vehicle_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('reservation_start_time', mysql.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('plate', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('import_price', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parking_id')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricula', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parking_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
