"""empty message

Revision ID: b9b5fd5f0dff
Revises: fd486a00a667
Create Date: 2025-02-28 16:58:57.991238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b5fd5f0dff'
down_revision = 'fd486a00a667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_logs_plate'), ['plate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_plate'))
        batch_op.drop_column('plate')

    # ### end Alembic commands ###
